### ISSUE TITLE
Select Max Instance Dialog broken with newest Sublime 3

### ISSUE THREAD

**Issue by cb109** [cb109/sublime3dsmax#14]
Trying to open the selection panel does nothing and prints the following error to the console:
```python
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File ".\sublime3dsmax.py", line 274, in run
Boost.Python.ArgumentError: Python argument types in
    Window.show_quick_panel(Window, list, function, int, int, function)
did not match C++ signature:
    show_quick_panel(class SP<struct edit_window::reference>, class boost::python::list, class boost::python::api::object)
    show_quick_panel(class SP<struct edit_window::reference>, class boost::python::list, class boost::python::api::object, unsigned int)
    show_quick_panel(class SP<struct edit_window::reference>, class boost::python::list, class boost::python::api::object, unsigned int, int)
```

**Comment by cb109** [comment]
Can not reproduce: Works fine for me with Build `3126`. Closing for now.
